### ISSUE TITLE
Overlapping DC block with routing wire

### ISSUE THREAD

**Issue by FatsieFS** [ChipFlow/mpw4#6]
@jpc-lip6
I have done locally a P&R. I do seem to see an overlap of the DC via blocks with a routing wire: ![DCWireOVL](https://user-images.githubusercontent.com/86363956/146678360-f1fac31b-1cd0-4144-abfe-0e1a5b40ee87.png)
This shows only met1 layer. I did have one failed route though so I don't know if it is related.

**Comment by FatsieFS** [comment]
Seems to also happen on met2/met3/met4

**Comment by FatsieFS** [comment]
After updating the routing gauge to square via in #5 , I still get the overlapping DC connection block to the routing wires.

**Comment by jpc-lip6** [comment]
Yes. I found the problem and corrected it. Not commited yet because the fix did trigger another bug that prevent the routing to complete.

I will commit the whole lot this evening or tomorrow once fully fixed.

**Comment by gatecat** [comment]
I think this can be closed now with the most recent Coriolis commits

**Comment by FatsieFS** [comment]
I rerun the PnR with latest Coriolis and latest version of StdCellLib and this issue seems to be solved.
